[package]
name = "cairo-rs-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "cairo_rs_py"
crate-type = ["cdylib"]

[features]
pypy = ["pyo3/num-bigint", "pyo3/extension-module"]
default = ["pyo3/num-bigint", "pyo3/auto-initialize"]

[dependencies]
pyo3 = { version = "0.16.5" }
cairo-rs = { path = "../cairo-rs" }
# cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "9753135843aaae4ba67855e6b652553d5f3809cf" }
num-bigint = "0.4"
lazy_static = "1.4.0"

[dev-dependencies.rusty-hook]
version = "0.11"
