[package]
name = "cairo-rs-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "cairo_rs_py"
crate-type = ["cdylib"]

[features]
pypy = ["pyo3/num-bigint", "pyo3/extension-module"]
default = ["pyo3/num-bigint", "pyo3/auto-initialize"]

[dependencies]
pyo3 = { version = "0.16.5" }
cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "a272cd2800eef209fef6caa02cb9a0efd1d70e50" }
num-bigint = "0.4"
lazy_static = "1.4.0"
