[package]
name = "cairo-rs-py"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.16.5", features = ["num-bigint"] }
cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "8e3541768cf8a01b4b8e50e427cef19cae56c9e2" }
num-bigint = "0.4"
lazy_static = "1.4.0"

[dev-dependencies.rusty-hook]
version = "0.11"

[features]
extension-module = ["pyo3/extension-module"]
embedded-python = ["pyo3/auto-initialize"]
default = ["extension-module"]

[lib]
name = "cairo_rs_py"
crate-type = ["cdylib"]
required-features = ["extension-module"]

[profile.release]
debug = 1
