[package]
name = "cairo-rs-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cairo_rs_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module", "num-bigint"] }
cairo-rs = { path = "../cairo-rs" }
num-bigint = "0.4"
lazy_static = "1.4.0"
