name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: cairo-rs-py
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
    - uses: actions/checkout@v3
    - name: Setup Pyenv
      uses: "gabrielfalcao/pyenv-action@v9"
      with:
        default: 3.9
    - name: Install test dependencies
      run: make deps-default-version
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
          fail_ci_if_error:     true
    - name: Cleanup tests
      run: make clean
