name: Running python tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v9"
      with:
        default: 3.7.2
        versions: 3.6.8, 3.5.7

    - name: Run python tests
      run: make run-python-test
