name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: Install pyenv 1/6
      run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - name: Install pyenv 2/6
      run:  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    - name: Install pyenv 3/6
      run:  echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
    - name: Install pyenv 4/6
      run:  exec "$SHELL"
    - name: Install pyenv 5/6
      run:   . ~/.bash_profile
    - name: Install pyenv 6/6
      run:  echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: make build
    - name: Run tests
      run: make full-test
    - name: Run clippy
      run: make clippy
    - name: Clean
      run: make clean
